services:
  - type: web
    name: hireguard-ai
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract